;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsList]
GameplayTagList=(Tag="Interactable",DevComment="Base interactable object")
GameplayTagList=(Tag="Interactable.TestObjects.ColourCube",DevComment="")
GameplayTagList=(Tag="Tasks.Actors.Waypoint",DevComment="")

